### ISSUE TITLE
support for laravel 5.3 `unauthorized` method

### ISSUE THREAD

**Issue by Yannik** [GrahamCampbell/Laravel-Exceptions#94]
Laravel 5.3 has an [App\Exceptions\Handler::unauthenticated](https://github.com/laravel/laravel/blob/master/app/Exceptions/Handler.php#L57) method.

This method should be called by [\Illuminate\Foundation\Exceptions\Handler::render()](https://github.com/laravel/framework/blob/5.3/src/Illuminate/Foundation/Exceptions/Handler.php#L128).

However, when changing the base class of `App\Exceptions\Handler` to `GrahamCampbell\Exceptions\NewExceptionHandler`, as required by this package, this does not work anymore, as `render` is overwritten by `ExceptionHandlerTrait`, therefore breaking default laravel behaviour.

**Comment by GrahamCampbell** [comment]
This package intentionally ignores that method because it doesn't fit with our design philosophy. The goal of this package isn't to perfectly mimic laravel's default behaviour, but to provide an opinionated alternative. Instead of calling the unauthenticated method, you should write a displayer class, and register it in the config.
